<?php
namespace BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use BlogBundle\Entity\Taxonomy;
use BlogBundle\Entity\Season;

/**
 * ChampionshiptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ChampionshipRepository extends EntityRepository
{
    public function findByTaxonomy($taxonomySlug, $type, $limit = null)
    {
        $championshipClass = $this->_entityName;
        $query = "SELECT a FROM $championshipClass a";
        $type2 = Season::STATUS_PRESENT;
        
        $query.=" INNER JOIN a.category tr";
        $query.=" INNER JOIN a.parent s";
        $query.=" INNER JOIN tr.term t
                  WHERE tr.type=:type AND t.slug=:taxonomySlug
                  AND s.status = :type2
                  ORDER BY a.startsAt DESC"
        ;

        $query = $this->getEntityManager()
            ->createQuery($query)
            ->setParameter("type",$type)
            ->setParameter("type2",$type2)
            ->setParameter('taxonomySlug',$taxonomySlug);

        if($limit)
        {
            $query->setMaxResults($limit);
        }

        $championships = $query->useQueryCache(true)->setQueryCacheLifetime(60)->getResult();

        return $championships;
    }
}