<?php
namespace BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use BlogBundle\Entity\Season;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CourseRepository extends EntityRepository
{
	public function findByName($slug, $id)
    {
        
        $eventClass = $this->_entityName;
        $status = Season::STATUS_PRESENT;

        $query = "SELECT c FROM $eventClass c ";

        $query.="
                  WHERE c.name = :slug
                  AND c.id=:id"
                  ;
    

        $results = $this->getEntityManager()
            ->createQuery($query)
            ->setParameter("slug", $slug)
            ->setParameter("id", $id);

        return $results->getOneOrNullResult();
    }

    public function findByArticle($id)
    {
        
        $eventClass = $this->_entityName;
        $status = Season::STATUS_PRESENT;

        $query = "SELECT c FROM $eventClass c ";
        $query.="WHERE c.article=:id";


        $results = $this->getEntityManager()
            ->createQuery($query)
            ->setParameter("id", $id);

        return $results->getOneOrNullResult();
    }
}