admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: %admin_path%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: %admin_path%

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

ed_blog_frontend:
    resource: "@EDBlogBundle/Controller/Frontend/"
    type:     annotation
    prefix:   /

msports_user:
    resource: "@MsportsUserBundle/Resources/config/routing.xml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

msports_event:
    resource: "@MsportsEventBundle/Controller/Frontend/"
    type:     annotation
    prefix:   /

msports_admin:
    resource: '@MsportsUserBundle/Resources/config/routing.yml'


