security:
    providers:
        admin:
            entity:
                class: Msports\UserBundle\Entity\Admin
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: "^%admin_path%"
            anonymous: true
            provider: admin
            form_login:
                login_path: "%admin_path%/login"
                check_path: "%admin_path%/login_check"
                default_target_path: "%admin_path%"
                remember_me: true
            logout:
                path: "%admin_path%/logout"
                target: "%admin_path%/login"
            remember_me:
                secret: "%secret%"

    role_hierarchy:
       ROLE_USER: ROLE_USER
       ROLE_ADMIN: [ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_SUPER_ADMIN]
       ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: "^%admin_path%/login", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%admin_path%/login_check", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%admin_path%", roles: [ROLE_SONATA_ADMIN] }

    encoders:
        Msports\UserBundle\Entity\Admin:
            algorithm: pbkdf2
            hash_algorithm: sha512
            encode_as_base64: true
            iterations: 5000
            key_length: 40


